# AIM: To design a ANN model for classification of Data and compute the performace metrics by eveluating the trained model. Also analyze its performance on real data by plotting the performace metrics.

# Use Pytorch Framework and NumPy, Pandas and matplotlib libraries

In [1]:
import torch
import numpy as np

In [2]:
import torch.nn as nn
import torch.optim as optim

# Define dataset: OR Gate / Import dataset

In [4]:
X = torch.tensor([[0.0,0.0],[0.0,1.0],[1.0,0.0],[1.0,1.0]])
y = torch.tensor([[0.0],[1.0],[1.0],[1.0]])
X

tensor([[0., 0.],
        [0., 1.],
        [1., 0.],
        [1., 1.]])

In [5]:
y

tensor([[0.],
        [1.],
        [1.],
        [1.]])

# Construct or Design a Neural network

In [6]:
class OR_ANN(nn.Module):
    def __init__(self):
        super(OR_ANN, self).__init__()
        self.linear = nn.Linear(2,1) # Inputs =2 output = 1
        self.sigmoid = nn.Sigmoid()

    def forward(self,x):
        x = self.linear(x)
        x = self.sigmoid(x)
        return x

# Instanciate the model with loss and optimizer

In [7]:
model = OR_ANN()
criterion = nn.BCELoss()  # Binary Cross-Entropy Loss
optimizer = optim.SGD(model.parameters(), lr=0.1)  # Stochastic Gradient Descent

# Now Lets Train the model

In [8]:
type(X)

torch.Tensor

In [9]:
inputs = torch.tensor([[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]])  # Input combinations
labels = torch.tensor([[0.0], [1.0], [1.0], [1.0]])  # Corresponding outputs for OR gate

In [10]:
# Modify training loop to collect loss values
losses = []
epochs = 1000
for epoch in range(epochs):
    outputs = model(inputs)
    loss = criterion(outputs, labels)
    losses.append(loss.item())
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if (epoch + 1) % 10 == 0:
        print(f'Epoch [{epoch + 1}/{epochs}], Loss: {loss.item():.4f}')

Epoch [10/1000], Loss: 0.6774
Epoch [20/1000], Loss: 0.5579
Epoch [30/1000], Loss: 0.4954
Epoch [40/1000], Loss: 0.4580
Epoch [50/1000], Loss: 0.4324
Epoch [60/1000], Loss: 0.4130
Epoch [70/1000], Loss: 0.3972
Epoch [80/1000], Loss: 0.3836
Epoch [90/1000], Loss: 0.3714
Epoch [100/1000], Loss: 0.3602
Epoch [110/1000], Loss: 0.3499
Epoch [120/1000], Loss: 0.3401
Epoch [130/1000], Loss: 0.3310
Epoch [140/1000], Loss: 0.3223
Epoch [150/1000], Loss: 0.3140
Epoch [160/1000], Loss: 0.3062
Epoch [170/1000], Loss: 0.2987
Epoch [180/1000], Loss: 0.2915
Epoch [190/1000], Loss: 0.2846
Epoch [200/1000], Loss: 0.2780
Epoch [210/1000], Loss: 0.2717
Epoch [220/1000], Loss: 0.2656
Epoch [230/1000], Loss: 0.2598
Epoch [240/1000], Loss: 0.2542
Epoch [250/1000], Loss: 0.2489
Epoch [260/1000], Loss: 0.2437
Epoch [270/1000], Loss: 0.2387
Epoch [280/1000], Loss: 0.2340
Epoch [290/1000], Loss: 0.2293
Epoch [300/1000], Loss: 0.2249
Epoch [310/1000], Loss: 0.2206
Epoch [320/1000], Loss: 0.2165
Epoch [330/1000],

# Test the model

In [11]:
with torch.no_grad():
    test_outputs = model(inputs)
    predicted = (test_outputs > 0.5).float()  # Convert probabilities to binary predictions
    print("\nTesting Results:")
    print("Inputs:\n", inputs.numpy())
    print("Predicted Outputs:\n", predicted.numpy())
    print("Actual Outputs:\n", labels.numpy())
    print(test_outputs)


Testing Results:
Inputs:
 [[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Predicted Outputs:
 [[0.]
 [1.]
 [1.]
 [1.]]
Actual Outputs:
 [[0.]
 [1.]
 [1.]
 [1.]]
tensor([[0.1901],
        [0.9254],
        [0.9272],
        [0.9985]])


# Evaluation and Visualization: Model Performance Evaluation

In [12]:
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, ConfusionMatrixDisplay

# Function to evaluate performance

In [ ]:
def evaluate_model(model, inputs, labels):
    with torch.no_grad():
        outputs = model(inputs)
        predicted = (outputs > 0.5).float()  # Convert probabilities to binary predictions

        # Calculate metrics
        accuracy = accuracy_score(labels.numpy().flatten(), predicted.numpy().flatten())
        precision = precision_score(labels.numpy().flatten(), predicted.numpy().flatten())
        recall = recall_score(labels.numpy().flatten(), predicted.numpy().flatten())
        f1 = f1_score(labels.numpy().flatten(), predicted.numpy().flatten())


        print("\nPerformance Metrics:")
        print(f"Accuracy: {accuracy:.2f}")
        print(f"Precision: {precision:.2f}")
        print(f"Recall: {recall:.2f}")
        print(f"F1 Score: {f1:.2f}")

        # Confusion Matrix
        cm = confusion_matrix(labels.numpy(), predicted.numpy())
        disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=[0, 1])
        disp.plot(cmap=plt.cm.Blues)
        plt.title("Confusion Matrix")
        plt.show()

In [ ]:
# Plot training loss
def plot_loss_curve(losses):
    plt.plot(losses, label="Training Loss")
    plt.xlabel("Epochs")
    plt.ylabel("Loss")
    plt.title("Loss Curve")
    plt.legend()
    plt.grid()
    plt.show()

In [ ]:
# Visualize decision boundary
def plot_decision_boundary(model):
    # Define the grid range for plotting
    x_min, x_max = -0.5, 1.5
    y_min, y_max = -0.5, 1.5
    xx, yy = torch.meshgrid(torch.linspace(x_min, x_max, 100), torch.linspace(y_min, y_max, 100))
    
    # Reshape the grid for model input
    grid = torch.cat([xx.reshape(-1, 1), yy.reshape(-1, 1)], dim=1)  # Shape: (10000, 2)
    
    with torch.no_grad():
        outputs = model(grid)  # Pass the grid through the model
        Z = (outputs > 0.5).float().reshape(xx.shape)  # Convert outputs to binary and reshape
    
    # Plot decision boundary
    plt.contourf(xx.numpy(), yy.numpy(), Z.numpy(), alpha=0.7, cmap=plt.cm.Paired)
    plt.scatter(inputs[:, 0].numpy(), inputs[:, 1].numpy(), c=labels.numpy().flatten(), edgecolor="k", cmap=plt.cm.Paired)
    plt.title("Decision Boundary")
    plt.xlabel("x1")
    plt.ylabel("x2")
    plt.show()

In [ ]:
# Evaluate and visualize
evaluate_model(model, inputs, labels)
plot_loss_curve(losses)
plot_decision_boundary(model)

# TO Replicate the same Code for XOR Gate with two layers

In [ ]:
# Define the XOR Neural Network Model
class XOR_ANN(nn.Module):
    def __init__(self):
        super(XOR_ANN, self).__init__()
        self.hidden = nn.Linear(2, 2)  # 2 input features, 4 hidden units
        self.output = nn.Linear(2, 1)  # 4 hidden units, 1 output
        self.sigmoid = nn.Sigmoid()  # Activation function for binary classification

    def forward(self, x):
        x = self.hidden(x)
        x = torch.relu(x)  # ReLU activation for the hidden layer
        x = self.output(x)
        x = self.sigmoid(x)  # Sigmoid activation for the output layer
        return x

In [ ]:
labels = torch.tensor([[0.0], [1.0], [1.0], [0.0]])  # Corresponding outputs for XOR gate

# Initialize model, loss function, and optimizer
model = XOR_ANN()
criterion = nn.BCELoss()  # Binary Cross-Entropy Loss
optimizer = optim.SGD(model.parameters(), lr=0.1)  # Stochastic Gradient Descent

# Training loop
epochs = 5000
losses = []
for epoch in range(epochs):
    # Forward pass
    outputs = model(inputs)
    loss = criterion(outputs, labels)
    losses.append(loss.item())

    # Backward pass and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # Print loss every 500 epochs
    if (epoch + 1) % 500 == 0:
        print(f'Epoch [{epoch + 1}/{epochs}], Loss: {loss.item():.4f}')

In [ ]:
# Evaluate and visualize
evaluate_model(model, inputs, labels)
plot_loss_curve(losses)
plot_decision_boundary(model)

# On Real Built - in dataset

In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Load and Preprocess the Iris Dataset

In [ ]:
# Load the Iris dataset
iris = load_iris()
X = iris.data  # Features: Sepal and petal lengths and widths
y = iris.target  # Labels: Iris species (0, 1, 2)
y

In [ ]:
# Encode labels if needed (already in numerical form for Iris dataset)
# Preprocess the data
scaler = StandardScaler()
X = scaler.fit_transform(X)  # Standardize the features for better training performance
X[0]

In [ ]:
# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Convert data to PyTorch tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.long)  # Long type for classification
y_test_tensor = torch.tensor(y_test, dtype=torch.long)

In [ ]:
X_train_tensor.shape

# Define the Neural Network Model

In [ ]:
class IrisMLP(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(IrisMLP, self).__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, output_dim)
        self.relu = nn.ReLU()  # Activation for hidden layers

    def forward(self, x):
        x = self.relu(self.fc1(x))
        x = self.fc2(x)  # Output layer (no activation since we use CrossEntropyLoss)
        return x

# Train the Model

In [ ]:
# Initialize the model, loss function, and optimizer
input_dim = X.shape[1]
hidden_dim = 16  # Arbitrary choice
output_dim = len(iris.target_names)  # 3 classes for Iris species

model = IrisMLP(input_dim, hidden_dim, output_dim)
criterion = nn.CrossEntropyLoss()  # For multi-class classification
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Training loop
epochs = 100
batch_size = 16
losses = []

for epoch in range(epochs):
    permutation = torch.randperm(X_train_tensor.size(0))
    epoch_loss = 0

    for i in range(0, X_train_tensor.size(0), batch_size):
        indices = permutation[i:i + batch_size]
        batch_x, batch_y = X_train_tensor[indices], y_train_tensor[indices]

        # Forward pass
        outputs = model(batch_x)
        loss = criterion(outputs, batch_y)
        epoch_loss += loss.item()

        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    losses.append(epoch_loss / len(X_train_tensor))
    if (epoch + 1) % 10 == 0:
        print(f"Epoch [{epoch + 1}/{epochs}], Loss: {epoch_loss / len(X_train_tensor):.4f}")

# Evaluate the Model and Make predictions on the test tensor

In [ ]:
# Evaluate the model on test data
with torch.no_grad():
    outputs = model(X_test_tensor)
    _, y_pred = torch.max(outputs, 1)  # Predicted class

# Accuracy
accuracy = accuracy_score(y_test_tensor.numpy(), y_pred.numpy())
print(f"\nTest Accuracy: {accuracy:.2f}")

# Confusion Matrix
cm = confusion_matrix(y_test_tensor.numpy(), y_pred.numpy())
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=iris.target_names)
disp.plot(cmap=plt.cm.Blues)
plt.title("Confusion Matrix")
plt.show()

In [ ]:
# Plot training loss
plt.plot(losses, label="Training Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.title("Loss Curve")
plt.legend()
plt.grid()
plt.show()

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay

In [ ]:
y_pred_np = y_pred.numpy()
y_test_np = y_test_tensor.numpy()
# Classification report
report = classification_report(y_test_np, y_pred_np, target_names=iris.target_names)
print("Classification Report:\n")
print(report)

# plot decision boundary with moons dataset 

In [ ]:
from sklearn.datasets import make_moons

In [ ]:
# Generate the dataset (binary classification)
X, y = make_moons(n_samples=1000, noise=0.2, random_state=42)

# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize the features (important for MLP performance)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Convert to PyTorch tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32).unsqueeze(1)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32).unsqueeze(1)

In [ ]:
class MoonsMLP(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super(MoonsMLP, self).__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.fc2 = nn.Linear(hidden_dim, output_dim)
        self.relu = nn.ReLU()
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.relu(self.fc1(x))
        x = self.fc2(x)
        return self.sigmoid(x)

In [ ]:
# Initialize the model, criterion, and optimizer
input_dim = X_train.shape[1]
hidden_dim = 16
output_dim = 1  # Binary classification
model = MoonsMLP(input_dim, hidden_dim, output_dim)
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

# Training loop
epochs = 1000
batch_size = 32
losses = []

for epoch in range(epochs):
    permutation = torch.randperm(X_train_tensor.size(0))
    epoch_loss = 0

    for i in range(0, X_train_tensor.size(0), batch_size):
        indices = permutation[i:i + batch_size]
        batch_x, batch_y = X_train_tensor[indices], y_train_tensor[indices]

        # Forward pass
        outputs = model(batch_x)
        loss = criterion(outputs, batch_y)
        epoch_loss += loss.item()

        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    losses.append(epoch_loss / len(X_train_tensor))
    if (epoch + 1) % 10 == 0:
        print(f"Epoch [{epoch + 1}/{epochs}], Loss: {epoch_loss / len(X_train_tensor):.4f}")

In [ ]:
# Function to plot decision boundary
def plot_decision_boundary(model, X, y, plot_title="Decision Boundary"):
    # Create a grid of points to evaluate the model
    h = .02  # Step size in the mesh
    x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
    y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
    xx, yy = np.meshgrid(np.arange(x_min, x_max, h),
                         np.arange(y_min, y_max, h))
    
    # Flatten the grid and make predictions
    grid_points = np.c_[xx.ravel(), yy.ravel()]
    grid_points_tensor = torch.tensor(grid_points, dtype=torch.float32)
    with torch.no_grad():
        Z = model(grid_points_tensor)
        Z = Z.numpy().reshape(xx.shape)
    
    # Plot the contour and training data
    plt.contourf(xx, yy, Z, alpha=0.8, cmap=plt.cm.RdBu)
    plt.scatter(X[:, 0], X[:, 1], c=y, edgecolors='k', marker='o', s=50, cmap=plt.cm.RdBu)
    plt.title(plot_title)
    plt.xlabel("Feature 1")
    plt.ylabel("Feature 2")
    plt.show()

# Plot the decision boundary for the test set
plot_decision_boundary(model, X_test, y_test)
